export const SECURITY_CONFIG = {
  PBKDF2_ITERATIONS: 100000,
  KEY_SIZE_WORDS: 8,
  SALT_SIZE_BYTES: 16,
  IV_SIZE_BYTES: 16,
  PRIVATE_KEY_SIZE_BYTES: 64,
  MIN_PASSWORD_LENGTH: 8,
  AUTO_LOCK_TIMEOUT_MS: 15 * 60 * 1000,
} as const;
